version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: Pp123456
            MYSQL_DATABASE: todo_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: mehmet
        networks:
            - trendnet
    myapp:
        image: mehmet2159/to-do
        restart: always
        depends_on:
            - database
        ports:
            - "8080:80"
        networks:
            - trendnet
networks:
    trendnet:
        driver: bridge

volumes:
    nginx:
        driver: local